name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST1: ${{ secrets.MY_GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - run: echo $TEST1

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: docker.selvas.com/      
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image-mason      
      run: |
        docker login $DOCKER_REPOSITORY -u mason.e.moon -p dmstlr22@@
        docker build . --file Dockerfile --tag $DOCKER_REPOSITORYnlp/mason/my-image-name:4144
        docker run -d $DOCKER_REPOSITORYnlp/mason/my-image-name:4144        
        docker push $DOCKER_REPOSITORYnlp/mason/my-image-name

