name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:
  gitenv_test:
    runs-on: ubuntu-latest
    steps:      
    -  run: echo $GITHUB_SHA # trigger된 commit SHA 출력됨    

  encrypted_test:
    runs-on: ubuntu-latest
    env:
      TEST1: ${{secrets.MY_GITHUB_TOKEN}} # token을 사용하여 암호화함
    steps:
    - uses: actions/checkout@v2
    - run: echo $TEST1 # Token에 적은 문자열이 *** 로 출력됨

  docker_test:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: docker.selvas.com 
      BUILD_IMAGE_TAG: ${DOCKER_REPOSITORY}/${GITHUB_REPOSITORY}:build
      REPOSITORY: docker.selvas.com # token이 아닌 변수로 활용
      VERSION: $GITHUB_REF

    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build and Push the Docker image-mason      
      run: |
        docker login ${DOCKER_REPOSITORY} -u mason.e.moon -p dmstlr22@@
        docker build -f Dockerfile -t $BUILD_IMAGE_TAG --build-arg VERSION=$VERSION .
        docker run -t --rm --privileged --name $GITHUB_REPOSITORY $BUILD_IMAGE_TAG
        docker push $REPOSITORY:$VERSION
