name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:
  token_test:
    runs-on: ubuntu-latest
    env:
      TEST1: ${{ secrets.MY_GITHUB_TOKEN}} # token을 사용하여 
    steps:
    - uses: actions/checkout@v2
    - run: echo $TEST1 

  docker_test:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: docker.selvas.com/ # token이 아닌 변수로 활용
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image-mason      
      run: |
        docker login ${DOCKER_REPOSITORY} -u mason.e.moon -p dmstlr22@@
        docker build . --file Dockerfile --tag ${DOCKER_REPOSITORY}nlp/mason/my-image-name:4144
        docker run -d ${DOCKER_REPOSITORY}nlp/mason/my-image-name:4144        
        docker push ${DOCKER_REPOSITORY}nlp/mason/my-image-name

