name: Docker Image CI

on:
  push:
    branches: [ main ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST1: ${{ secrets.MY_GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - run: echo $TEST1

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image-mason      
      run: |
        docker login docker.selvas.com/ -u mason.e.moon -p dmstlr22@@
        docker build . --file Dockerfile --tag docker.selvas.com/nlp/mason/my-image-name:4144
        docker run -d docker.selvas.com/nlp/mason/my-image-name:4144        
        docker push docker.selvas.com/nlp/mason/my-image-name

