name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image-mason
      with:
        registry: docker.selvas.com/
        username: mason.e.moon
        password: dmstlr22@@
      run: |
        docker build . --file Dockerfile --tag my-image-name:4144
        docker run my-image-name:4144
        docker login docker.selvas.com/
#        docker push docker.selvas.com/mason/my-image-name:4144



    
  